In [1]:
import numpy as np
import random as rd
import pandas as pd
import sys
sys.path.insert(0, '../src/model/')
sys.path.insert(1, '../src/view/')
from Taixxa import Taixxa
from FitnessViewer import FitnessViewer
from FitnessComparator import FitnessComparator

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 1 Axes>

In [ ]:
data = Taixxa()
data.loadFile("tai60a.dat")
data2 = Taixxa()
data2.loadFile("tai60a.dat")
data3 = Taixxa()
data3.loadFile("tai12a.dat")
data4 = Taixxa()
data4.loadFile("tai12a.dat")
sol, fit1 = data.simulatedAnnealing(30, 0.9,100,11)
sol, fit2 = data2.tabuSearch(1000, 22)
fit1 = np.array(fit1)
fit2 = np.array(fit2)

lists = list([fit1,fit2])
df = pd.concat([pd.Series(x) for x in lists], axis=1)
comp = FitnessComparator(df)
comp.plot()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [29]:
solPerfect = [8,1,6,2,11,10,3,5,9,7,12,4]
solPerfect = list(map(lambda x: x-1, solPerfect))
mincost = data.computeCost(solPerfect)
mincostfound = data.computeCost()
mincostfound2 = data2.computeCost()
print(mincost)
print(mincostfound)
print(mincostfound2)

224416
271440
246614


In [3]:
print(data.weights)

[[79  0 98 ... 69 81 99]
 [71 98  0 ... 17 24 27]
 [ 7 76 83 ...  3 71 61]
 ...
 [64 69 17 ...  0 73 78]
 [87 81 24 ... 73  0  3]
 [53 99 27 ... 78  3  0]]
