In [1]:
import numpy as np
import random as rd
import pandas as pd
import sys
sys.path.insert(0, '../src/model/')
sys.path.insert(1, '../src/view/')
from Taixxa import Taixxa
from FitnessViewer import FitnessViewer
from FitnessComparator import FitnessComparator

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 1 Axes>

In [2]:
data = Taixxa()
data.loadFile("tai12a.dat")
data2 = Taixxa()
data2.loadFile("tai12a.dat")
print("simulated annealing ....")
sol, fit1 = data.simulatedAnnealing(30, 0.9,100,11)
print("tabu search ....")
sol, fit2 = data2.tabuSearch(1000, 22)
fit1 = np.array(fit1)
fit2 = np.array(fit2)

lists = list([fit1,fit2])
df = pd.concat([pd.Series(x) for x in lists], axis=1)
comp = FitnessComparator(df)
comp.plot()

27
[[ 0 21 95 82 56 41  6 25 10  4 63  6]
 [21  0 44 40 75 79  0 89 35  9  1 85]
 [95 44  0 84 12  0 26 91 11 35 82 26]
 [82 40 84  0 69 56 86 45 91 59 18 76]
 [56 75 12 69  0 39 18 57 36 61 36 21]
 [41 79  0 56 39  0 71 11 29 82 82  6]
 [ 6  0 26 86 18 71  0 71  8 77 74 30]
 [25 89 91 45 57 11 71  0 89 76 76 40]
 [10 35 11 91 36 29  8 89  0 93 56  1]
 [ 4  9 35 59 61 82 77 76 93  0 50  4]
 [63  1 82 18 36 82 74 76 56 50  0 36]
 [ 6 85 26 76 21  6 30 40  1  4 36  0]]
[[ 0 27 85  2  1 15 11 35 11 20 21 61]
 [27  0 80 58 21 76 72 44 85 94 90 51]
 [85 80  0  3 48 29 90 66 41 15 83 96]
 [ 2 58  3  0 74 45 65 40 54 83 14 71]
 [ 1 21 48 74  0 77 36 53 37 26 87 76]
 [15 76 29 45 77  0 91 13 29 11 77 32]
 [11 72 90 65 36 91  0 87 67 94 79  2]
 [35 44 66 40 53 13 87  0 10 99 56 70]
 [11 85 41 54 37 29 67 10  0 99 60  4]
 [20 94 15 83 26 11 94 99 99  0 56  2]
 [21 90 83 14 87 77 79 56 60 56  0 60]]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
27
[[ 0 21 95 82 56 41  6 25 10  4 63  6]
 [21  0 44 40 75 

IndexError: index 11 is out of bounds for axis 0 with size 11

In [29]:
solPerfect = [8,1,6,2,11,10,3,5,9,7,12,4]
solPerfect = list(map(lambda x: x-1, solPerfect))
mincost = data.computeCost(solPerfect)
mincostfound = data.computeCost()
mincostfound2 = data2.computeCost()
print(mincost)
print(mincostfound)
print(mincostfound2)

224416
271440
246614
